using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace immigrationLib
{
    public abstract class Countries
    {
        public static Dictionary<int, string> countries = new Dictionary<int, string>()
        {
            {0, "Afghanistan"},
            {1, "Albania"},
            {2, "Algeria"},
            {3, "Andorra"},
            {4, "Angola"},
            {5, "Antigua and Barbuda"},
            {6, "Argentina"},
            {7, "Armenia"},
            {8, "Australia"},
            {9, "Austria"},
            {10, "Azerbaijan"},
            {11, "Bahamas"},
            {12, "Bahrain"},
            {13, "Bangladesh"},
            {14, "Barbados"},
            {15, "Belarus"},
            {16, "Belgium"},
            {17, "Belize"},
            {18, "Benin"},
            {19, "Bhutan"},
            {20, "Bolivia"},
            {21, "Bosnia and Herzegovina"},
            {22, "Botswana"},
            {23, "Brazil"},
            {24, "Brunei"},
            {25, "Bulgaria"},
            {26, "Burkina Faso"},
            {27, "Burundi"},
            {28, "Cabo Verde"},
            {29, "Cambodia"},
            {30, "Cameroon"},
            {31, "Canada"},
            {32, "Central African Republic"},
            {33, "Chad"},
            {34, "Chile"},
            {35, "China"},
            {36, "Colombia"},
            {37, "Comoros"},
            {38, "Congo (Congo-Brazzaville)"},
            {39, "Costa Rica"},
            {40, "Croatia"},
            {41, "Cuba"},
            {42, "Cyprus"},
            {43, "Czechia (Czech Republic)"},
            {44, "Denmark"},
            {45, "Djibouti"},
            {46, "Dominica"},
            {47, "Dominican Republic"},
            {48, "Ecuador"},
            {49, "Egypt"},
            {50, "El Salvador"},
            {51, "Equatorial Guinea"},
            {52, "Eritrea"},
            {53, "Estonia"},
            {54, "Eswatini (fmr. Swaziland)"},
            {55, "Ethiopia"},
            {56, "Fiji"},
            {57, "Finland"},
            {58, "France"},
            {59, "Gabon"},
            {60, "Gambia"},
            {61, "Georgia"},
            {62, "Germany"},
            {63, "Ghana"},
            {64, "Greece"},
            {65, "Grenada"},
            {66, "Guatemala"},
            {67, "Guinea"},
            {68, "Guinea-Bissau"},
            {69, "Guyana"},
            {70, "Haiti"},
            {71, "Holy See"},
            {72, "Honduras"},
            {73, "Hungary"},
            {74, "Iceland"},
            {75, "India"},
            {76, "Indonesia"},
            {77, "Iran"},
            {78, "Iraq"},
            {79, "Ireland"},
            {80, "Israel"},
            {81, "Italy"},
            {82, "Jamaica"},
            {83, "Japan"},
            {84, "Jordan"},
            {85, "Kazakhstan"},
            {86, "Kenya"},
            {87, "Kiribati"},
            {88, "Kuwait"},
            {89, "Kyrgyzstan"},
            {90, "Laos"},
            {91, "Latvia"},
            {92, "Lebanon"},
            {93, "Lesotho"},
            {94, "Liberia"},
            {95, "Libya"},
            {96, "Liechtenstein"},
            {97, "Lithuania"},
            {98, "Luxembourg"},
            {99, "Madagascar"},
            {100, "Malawi"},
            {101, "Malaysia"},
            {102, "Maldives"},
            {103, "Mali"},
            {104, "Malta"},
            {105, "Marshall Islands"},
            {106, "Mauritania"},
            {107, "Mauritius"},
            {108, "Mexico"},
            {109, "Micronesia"},
            {110, "Moldova"},
            {111, "Monaco"},
            {112, "Mongolia"},
            {113, "Montenegro"},
            {114, "Morocco"},
            {115, "Mozambique"},
            {116, "Myanmar (formerly Burma)"},
            {117, "Namibia"},
            {118, "Nauru"},
            {119, "Nepal"},
            {120, "Netherlands"},
            {121, "New Zealand"},
            {122, "Nicaragua"},
            {123, "Niger"},
            {124, "Nigeria"},
            {125, "North Korea"},
            {126, "North Macedonia (formerly Macedonia)"},
            {127, "Norway"},
            {128, "Oman"},
            {129, "Pakistan"},
            {130, "Palau"},
            {131, "Palestine State"},
            {132, "Panama"},
            {133, "Papua New Guinea"},
            {134, "Paraguay"},
            {135, "Peru"},
            {136, "Philippines"},
            {137, "Poland"},
            {138, "Portugal"},
            {139, "Qatar"},
            {140, "Romania"},
            {141, "Russia"},
            {142, "Rwanda"},
            {143, "Saint Kitts and Nevis"},
            {144, "Saint Lucia"},
            {145, "Saint Vincent and the Grenadines"},
            {146, "Samoa"},
            {147, "San Marino"},
            {148, "Sao Tome and Principe"},
            {149, "Saudi Arabia"},
            {150, "Senegal"},
            {151, "Serbia"},
            {152, "Seychelles"},
            {153, "Sierra Leone"},
            {154, "Singapore"},
            {155, "Slovakia"},
            {156, "Slovenia"},
            {157, "Solomon Islands"},
            {158, "Somalia"},
            {159, "South Africa"},
            {160, "South Korea"},
            {161, "South Sudan"},
            {162, "Spain"},
            {163, "Sri Lanka"},
            {164, "Sudan"},
            {165, "Suriname"},
            {166, "Sweden"},
            {167, "Switzerland"},
            {168, "Syria"},
            {169, "Tajikistan"},
            {170, "Tanzania"},
            {171, "Thailand"},
            {172, "Timor-Leste"},
            {173, "Togo"},
            {174, "Tonga"},
            {175, "Trinidad and Tobago"},
            {176, "Tunisia"},
            {177, "Turkey"},
            {178, "Turkmenistan"},
            {179, "Tuvalu"},
            {180, "Uganda"},
            {181, "Ukraine"},
            {182, "United Arab Emirates"},
            {183, "United Kingdom"},
            {184, "United States of America"},
            {185, "Uruguay"},
            {186, "Uzbekistan"},
            {187, "Vanuatu"},
            {188, "Venezuela"},
            {189, "Vietnam"},
            {190, "Yemen"},
            {191, "Zambia"},
            {192, "Zimbabwe"}
        };
    }
}
